document.addEventListener('DOMContentLoaded', function() {
    const fraseElement = document.getElementById('frase');
    const explicacionElement = document.getElementById('explicacion'); // Obtenemos el elemento de la explicación

    // Constante con la lista de frases y sus explicaciones
    const datosSabiasQue = [
        { frase: "Un estornudo viaja a más de 160 km/h.", explicacion: "Un estornudo es una reacción involuntaria del cuerpo para expulsar irritantes de las vías respiratorias. La velocidad a la que viaja el aire puede ser sorprendente debido a la fuerza con la que se contraen los músculos respiratorios." },
        { frase: "Las uñas crecen más rápido en la mano dominante.", explicacion: "La razón exacta no se comprende completamente, pero se cree que un mayor uso y, por lo tanto, una mayor circulación sanguínea en la mano dominante, podría estimular un crecimiento más rápido de las uñas." },
        { frase: "El ojo humano distingue 10 millones de colores.", explicacion: "El ojo humano posee millones de células fotorreceptoras llamadas conos que son sensibles a diferentes longitudes de onda de luz (rojo, verde, azul), permitiendo al cerebro percibir una vasta gama de colores a través de sus combinaciones." },
        { frase: "Más bacterias en la boca que personas en el mundo.", explicacion: "La boca humana es un ecosistema complejo y alberga cientos de especies diferentes de bacterias. Muchas de estas bacterias son inofensivas e incluso beneficiosas para la salud bucal y digestiva." },
        { frase: "La risa es contagiosa por las neuronas espejo.", explicacion: "Las neuronas espejo son un tipo de neuronas que se activan tanto cuando realizamos una acción como cuando observamos a alguien más realizando la misma acción. Se cree que son fundamentales para la empatía y la imitación, lo que explica por qué la risa o el bostezo pueden ser 'contagiosos'." },
        { frase: "El cerebro humano pesa 1.4 kg.", explicacion: "Aunque es una parte relativamente pequeña del cuerpo, el cerebro consume una cantidad desproporcionada de energía y oxígeno. Su peso de alrededor de 1.4 kg en adultos es promedio, pero su complejidad funcional es inmensa." },
        { frase: "El fémur es el hueso más fuerte.", explicacion: "El fémur, ubicado en el muslo, es el hueso más largo y fuerte del cuerpo humano. Su robustez le permite soportar el peso corporal y las fuerzas generadas durante actividades como caminar, correr y saltar." },
        { frase: "Saliva para llenar dos piscinas en la vida.", explicacion: "A lo largo de la vida, una persona produce una cantidad asombrosa de saliva. La saliva es esencial para la digestión, la lubricación de la boca y la protección contra bacterias, entre otras funciones vitales." },
        { frase: "El corazón late 100,000 veces al día.", explicacion: "El corazón humano es un músculo increíblemente trabajador que bombea sangre continuamente para suministrar oxígeno y nutrientes a todo el cuerpo. Este ritmo constante de aproximadamente 100,000 latidos diarios demuestra su vital importancia." },
        { frase: "El pelo crece 15 cm al año.", explicacion: "El crecimiento del cabello varía entre individuos y factores como la genética, la dieta y la salud general. En promedio, el cabello humano crece alrededor de 1.25 centímetros (aproximadamente media pulgada) al mes, sumando unos 15 cm al año." },
        { frase: "La jirafa se limpia las orejas con la lengua.", explicacion: "Las jirafas tienen lenguas muy largas, que pueden medir hasta 45 centímetros (18 pulgadas). Esta adaptación les permite alcanzar y limpiar sus propias orejas, así como deshojar las ramas de los árboles que comen." },
        { frase: "El colibrí vuela hacia atrás.", explicacion: "Los colibríes son las únicas aves capaces de volar hacia atrás. Su estructura alar única y la capacidad de rotar sus alas 180 grados les permiten una maniobrabilidad aérea excepcional, incluyendo el vuelo estacionario y hacia atrás." },
        { frase: "El guepardo es el más rápido.", explicacion: "El guepardo es el animal terrestre más rápido, capaz de alcanzar velocidades de hasta 110-120 kilómetros por hora (70-75 mph) en carreras cortas. Está diseñado para la velocidad, con un cuerpo ligero y flexible, y garras no retráctiles para una mejor tracción." },
        { frase: "El elefante no puede saltar.", explicacion: "Los elefantes, a pesar de su tamaño y fuerza, no pueden saltar. Esto se debe a la estructura de sus patas, que no están adaptadas para el despegue vertical, y a que no tienen los mismos músculos de la pantorrilla que la mayoría de los mamíferos capaces de saltar." },
        { frase: "La lengua de ballena azul pesa como un elefante.", explicacion: "La ballena azul es el animal más grande de la Tierra, y su lengua puede pesar hasta 4 toneladas, lo que es comparable al peso de un elefante adulto. Esta enorme lengua es crucial para su alimentación por filtración." },
        { frase: "Gusanos regeneran partes del cuerpo.", explicacion: "Algunas especies de gusanos, como las planarias, tienen una notable capacidad de regeneración. Si se les corta en varias partes, cada fragmento puede regenerar un gusano completo, incluyendo su cabeza y órganos internos." },
        { frase: "Los ojos del camaleón se mueven independientemente.", explicacion: "Los camaleones tienen una visión excepcional. Sus ojos pueden moverse de forma independiente el uno del otro, lo que les permite observar dos direcciones diferentes a la vez, una adaptación clave para la caza y la detección de depredadores." },
        { frase: "El calamar gigante tiene los ojos más grandes.", explicacion: "El calamar gigante posee los ojos más grandes de cualquier criatura viviente, llegando a tener un diámetro de hasta 27 centímetros (11 pulgadas). Estos ojos enormes son una adaptación para ver en las profundidades oscuras del océano." },
        { frase: "Las estrellas de mar no tienen cerebro ni sangre.", explicacion: "Las estrellas de mar, o asteroideos, no poseen un cerebro centralizado. Su sistema nervioso es una red descentralizada. En lugar de sangre, utilizan agua de mar que circula a través de un sistema vascular acuífero." },
        { frase: "Las mariposas saborean con los pies.", explicacion: "Las mariposas tienen receptores del gusto en sus patas, específicamente en sus tarsos. Esto les permite 'probar' las plantas sobre las que se posan para determinar si son adecuadas para poner huevos o si contienen néctar." },
        { frase: "El sonido viaja 4 veces más rápido en el agua.", explicacion: "La velocidad del sonido depende del medio a través del cual viaja. En el agua, que es más densa e incompresible que el aire, las moléculas están más juntas, lo que permite que las ondas sonoras se transmitan más rápidamente." },
        { frase: "Un rayo alcanza 30,000 °C.", explicacion: "Un rayo es una descarga eléctrica atmosférica poderosa. La temperatura del canal de un rayo puede ser extremadamente alta, superando la temperatura de la superficie del Sol, debido a la inmensa energía liberada en un corto período de tiempo." },
        { frase: "El sol es una estrella mediana.", explicacion: "Aunque el Sol es enorme en comparación con la Tierra, en el contexto del universo y otras estrellas, es considerado una estrella de tamaño mediano (una enana amarilla). Existen estrellas mucho más grandes y masivas que nuestro Sol." },
        { frase: "La Tierra tiene agua líquida.", explicacion: "La presencia de agua líquida en la superficie es una característica fundamental que distingue a la Tierra y es esencial para la vida tal como la conocemos. Su órbita en la 'zona habitable' y su atmósfera permiten que el agua se mantenga en este estado." },
        { frase: "Júpiter es el planeta más grande.", explicacion: "Júpiter es el planeta más grande de nuestro sistema solar, con una masa que es dos veces y media la de todos los demás planetas combinados. Es un gigante gaseoso compuesto principalmente de hidrógeno y helio." },
        { frase: "Saturno tiene anillos de hielo y roca.", explicacion: "Los impresionantes anillos de Saturno están compuestos por miles de millones de partículas de hielo de agua y roca. Se cree que estos anillos son restos de cometas, asteroides o lunas destrozadas por la gravedad de Saturno." },
        { frase: "Urano gira de lado.", explicacion: "Urano es único en nuestro sistema solar porque su eje de rotación está inclinado casi 98 grados con respecto a su órbita alrededor del Sol. Esto significa que parece 'rodar' sobre su costado mientras orbita." },
        { frase: "Neptuno es el más ventoso.", explicacion: "Neptuno es conocido por sus vientos extremadamente fuertes, que pueden alcanzar velocidades de hasta 2,100 kilómetros por hora (1,300 mph), las más rápidas de cualquier planeta en nuestro sistema solar. Estos vientos impulsan tormentas gigantescas." },
        { frase: "Plutón es un planeta enano.", explicacion: "Plutón fue reclasificado como 'planeta enano' en 2006 por la Unión Astronómica Internacional. Aunque es esférico y orbita el Sol, no ha 'limpiado' su órbita de otros objetos, lo que es uno de los criterios para ser considerado un planeta completo." },
        { frase: "La Vía Láctea es espiral.", explicacion: "Nuestra galaxia, la Vía Láctea, es una galaxia espiral barrada. Esto significa que tiene una barra central de estrellas y dos o más brazos espirales que se extienden desde el centro, donde reside la mayoría de las estrellas, gas y polvo." },
        { frase: "Miles de millones de galaxias.", explicacion: "El universo observable contiene un número inmenso de galaxias, que se estima en cientos de miles de millones. Cada galaxia, a su vez, contiene miles de millones de estrellas, planetas y otros cuerpos celestes." },
        { frase: "La luz del sol tarda 8 minutos y 20 segundos.", explicacion: "La luz viaja a una velocidad finita. Debido a la gran distancia entre el Sol y la Tierra (aproximadamente 150 millones de kilómetros o 93 millones de millas), la luz del Sol tarda unos 8 minutos y 20 segundos en llegar a nuestro planeta." },
        { frase: "Un año luz es distancia.", explicacion: "Un año luz no es una medida de tiempo, sino de distancia. Representa la distancia que la luz viaja en un año terrestre en el vacío, que es aproximadamente 9.46 billones de kilómetros (5.88 billones de millas)." },
        { frase: "Agujeros negros: gravedad extrema.", explicacion: "Un agujero negro es una región del espacio-tiempo donde la gravedad es tan fuerte que nada, ni siquiera la luz u otras partículas electromagnéticas, puede escapar de ella. Se forman a partir de los restos de estrellas muy masivas que colapsan." },
        { frase: "El universo tiene 13.8 mil millones de años.", explicacion: "Según las mediciones cosmológicas actuales, la edad del universo desde el Big Bang se estima en aproximadamente 13.8 mil millones de años. Esta estimación se basa en la tasa de expansión del universo y la radiación de fondo de microondas." },
        { frase: "El agua tiene tres estados.", explicacion: "El agua (H2O) es una de las pocas sustancias que se encuentra naturalmente en los tres estados de la materia en la Tierra: sólido (hielo), líquido (agua) y gaseoso (vapor de agua). Los cambios entre estos estados ocurren con cambios de temperatura y presión." },
        { frase: "El agua hierve a 100 °C.", explicacion: "A nivel del mar y bajo la presión atmosférica estándar, el punto de ebullición del agua es de 100 grados Celsius (212 grados Fahrenheit). A esta temperatura, el agua líquida se convierte en vapor." },
        { frase: "El agua se congela a 0 °C.", explicacion: "A nivel del mar y bajo la presión atmosférica estándar, el punto de congelación del agua es de 0 grados Celsius (32 grados Fahrenheit). A esta temperatura, el agua líquida se convierte en hielo." },
        { frase: "El hielo flota por ser menos denso.", explicacion: "A diferencia de la mayoría de las sustancias, el agua se vuelve menos densa cuando se congela. Las moléculas de agua forman una estructura cristalina abierta en el hielo, lo que hace que ocupe más volumen y, por lo tanto, flote en el agua líquida." },
        { frase: "El agua pura no conduce electricidad.", explicacion: "El agua pura (destilada) es un mal conductor de electricidad. Son las impurezas y los iones disueltos en el agua (como sales y minerales) los que le permiten conducir la electricidad. El agua de grifo, por ejemplo, contiene iones." },
        { frase: "El aire es nitrógeno y oxígeno.", explicacion: "El aire que respiramos es una mezcla de gases. Aproximadamente el 78% es nitrógeno, el 21% es oxígeno y el 1% restante está compuesto por otros gases como argón, dióxido de carbono y trazas de otros elementos." },
        { frase: "El oxígeno es esencial.", explicacion: "El oxígeno (O2) es un gas incoloro, inodoro e insípido que es vital para la vida de la mayoría de los organismos en la Tierra, incluyendo los humanos. Es fundamental para la respiración celular, el proceso que convierte los alimentos en energía." },
        { frase: "El dióxido de carbono es de efecto invernadero.", explicacion: "El dióxido de carbono (CO2) es un gas natural en la atmósfera y también un subproducto de actividades humanas. Es un gas de efecto invernadero clave que atrapa el calor en la atmósfera terrestre, contribuyendo al calentamiento global." },
        { frase: "El ozono protege de la radiación UV.", explicacion: "La capa de ozono, una región de la estratosfera terrestre, contiene una alta concentración de ozono (O3). Esta capa actúa como un escudo, absorbiendo la mayor parte de la dañina radiación ultravioleta (UV) del Sol, protegiendo la vida en la Tierra." },
        { frase: "El viento es aire en movimiento.", explicacion: "El viento es el movimiento del aire en la atmósfera, causado por diferencias en la presión atmosférica. El aire se mueve de áreas de alta presión a áreas de baja presión. La fuerza y dirección del viento son influenciadas por la rotación de la Tierra." },
        { frase: "Las nubes son gotitas de agua o hielo.", explicacion: "Las nubes son masas visibles de pequeñas gotitas de agua líquida o cristales de hielo suspendidas en la atmósfera. Se forman cuando el vapor de agua en el aire se enfría y se condensa alrededor de partículas diminutas (núcleos de condensación)." },
        { frase: "La lluvia es agua que cae.", explicacion: "La lluvia es una forma de precipitación donde el agua cae de las nubes en forma líquida. Se produce cuando las gotitas de agua o cristales de hielo en las nubes crecen lo suficiente como para vencer la resistencia del aire y caen a la superficie terrestre." },
        { frase: "La nieve es agua congelada que cae.", explicacion: "La nieve es una forma de precipitación sólida que consiste en cristales de hielo. Se forma en las nubes cuando la temperatura es lo suficientemente baja como para que el vapor de agua se convierta directamente en hielo sin pasar por el estado líquido." },
        { frase: "El granizo son bolas de hielo.", explicacion: "El granizo son precipitaciones en forma de bolas o trozos irregulares de hielo. Se forman en tormentas fuertes, cuando las corrientes ascendentes llevan gotas de agua a altitudes frías, donde se congelan y se les adhieren más capas de hielo." },
        { frase: "El arcoíris es un fenómeno óptico.", explicacion: "Un arcoíris es un fenómeno óptico y meteorológico que resulta de la refracción y reflexión de la luz solar en las gotas de agua en la atmósfera. Aparece como un arco multicolor debido a la dispersión de la luz en sus diferentes longitudes de onda." },
        { frase: "El primer vuelo fue en 1903.", explicacion: "El primer vuelo controlado, sostenido y propulsado de una aeronave más pesada que el aire fue realizado por los hermanos Wright el 17 de diciembre de 1903, con su aeronave 'Wright Flyer' en Kitty Hawk, Carolina del Norte." },
        { frase: "El primer coche en 1885.", explicacion: "Karl Benz es considerado el inventor del primer automóvil de gasolina práctico. Su 'Motorwagen' de tres ruedas, construido en 1885, es ampliamente reconocido como el primer automóvil moderno. Recibió la patente en 1886." },
        { frase: "El primer teléfono en 1876.", explicacion: "Alexander Graham Bell recibió la patente por el teléfono en 1876. Aunque hubo controversias y otros inventores trabajaron en tecnologías similares, la patente de Bell es reconocida por el desarrollo del dispositivo para transmitir la voz electrónicamente." },
        { frase: "La primera bombilla en 1879.", explicacion: "Thomas Edison es ampliamente acreditado con la invención de la bombilla incandescente práctica y duradera en 1879. Aunque otros inventores también trabajaron en la tecnología, Edison desarrolló un filamento de carbono de larga duración que hizo la bombilla comercialmente viable." },
        { frase: "La primera computadora en la década de 1830.", explicacion: "Charles Babbage diseñó la 'Máquina Analítica' en la década de 1830, que es considerada el precursor del ordenador moderno. Aunque nunca se construyó completamente en su época, sus principios de diseño eran sorprendentemente avanzados y sentaron las bases de la computación." },
        { frase: "El primer SMS fue en 1992.", explicacion: "El primer mensaje de texto SMS (Short Message Service) fue enviado el 3 de diciembre de 1992 por Neil Papworth, un ingeniero de Vodafone, desde una computadora a un teléfono móvil. El mensaje decía 'Merry Christmas'." },
        { frase: "El primer sitio web fue en 1991.", explicacion: "El primer sitio web fue creado por Tim Berners-Lee y puesto en línea en 1991 en CERN (Organización Europea para la Investigación Nuclear). El sitio explicaba qué era la World Wide Web y cómo usarla." },
        { frase: "El primer correo electrónico en 1971.", explicacion: "Ray Tomlinson es acreditado con la invención del correo electrónico en 1971. Fue el primero en enviar un mensaje entre dos computadoras diferentes usando el símbolo '@' para separar el nombre del usuario del nombre de la máquina." },
        { frase: "El primer videojuego en la década de 1950.", explicacion: "Aunque hay debates sobre cuál fue el 'primer' videojuego, uno de los primeros ejemplos interactivos fue 'Tennis for Two', creado por William Higinbotham en 1958, el cual se jugaba en un osciloscopio." },
        { frase: "El primer programa de televisión en la década de 1930.", explicacion: "Aunque las transmisiones experimentales comenzaron antes, los primeros programas de televisión regulares y públicos se iniciaron en la década de 1930, notablemente por la BBC en el Reino Unido y estaciones en Estados Unidos." },
        { frase: "La Gran Muralla China tiene más de 20,000 km.", explicacion: "La Gran Muralla China es una serie de fortificaciones antiguas construidas para proteger las fronteras de China. Su longitud total, incluyendo todas sus ramas, se estima en más de 21,196 kilómetros (13,171 millas)." },
        { frase: "La Torre Eiffel mide 324 metros.", explicacion: "La Torre Eiffel en París, Francia, fue construida para la Exposición Universal de 1889. Su altura total, incluyendo su antena, es de 324 metros (1,063 pies). Fue la estructura más alta del mundo durante 41 años." },
        { frase: "El Coliseo albergaba a 50,000 personas.", explicacion: "El Coliseo de Roma, un anfiteatro elíptico, fue construido en el siglo I d.C. Era capaz de albergar a entre 50,000 y 80,000 espectadores que asistían a combates de gladiadores y otros espectáculos públicos." },
        { frase: "Las Pirámides de Giza son tumbas.", explicacion: "Las Grandes Pirámides de Giza en Egipto son monumentales estructuras construidas como tumbas para los faraones de la Cuarta Dinastía. Son los únicos monumentos de las Siete Maravillas del Mundo Antiguo que aún permanecen en gran parte intactos." },
        { frase: "El Taj Mahal es un mausoleo.", explicacion: "El Taj Mahal en Agra, India, es un impresionante mausoleo de mármol blanco construido por el emperador mogol Shah Jahan en memoria de su esposa favorita, Mumtaz Mahal. Es considerado una obra maestra de la arquitectura mogol." },
        { frase: "La Estatua de la Libertad fue un regalo.", explicacion: "La Estatua de la Libertad, ubicada en la Isla de la Libertad en Nueva York, fue un regalo del pueblo de Francia a los Estados Unidos para conmemorar el centenario de la independencia estadounidense. Fue diseñada por Frédéric Auguste Bartholdi." },
        { frase: "El Big Ben es una campana.", explicacion: "Aunque comúnmente se conoce como 'Big Ben' a toda la torre del reloj en el Palacio de Westminster en Londres, el nombre en realidad se refiere a la gran campana que se encuentra dentro de la torre. La torre ahora se llama oficialmente 'Elizabeth Tower'." },
        { frase: "La Ópera de Sídney tiene forma de concha.", explicacion: "La Ópera de Sídney, en Australia, es famosa por su diseño distintivo con una serie de 'conchas' en forma de velas. Es uno de los edificios más reconocibles del siglo XX y un Patrimonio de la Humanidad de la UNESCO." },
        { frase: "El Cristo Redentor está en Río.", explicacion: "La estatua del Cristo Redentor se encuentra en la cima del Cerro del Corcovado en Río de Janeiro, Brasil. Es un ícono cultural tanto de Río como de Brasil y es una de las Nuevas Siete Maravillas del Mundo." },
        { frase: "Machu Picchu es una ciudadela inca.", explicacion: "Machu Picchu es una antigua ciudadela inca situada en los Andes de Perú. Fue construida en el siglo XV y es un impresionante ejemplo de arquitectura inca, con terrazas agrícolas, templos y residencias, en un entorno montañoso espectacular." },
        { frase: "El primer sello fue el Penny Black.", explicacion: "El Penny Black fue el primer sello postal adhesivo del mundo, emitido por el Reino Unido el 1 de mayo de 1840. Su introducción revolucionó el envío de correo al hacer que el remitente pagara por adelantado, estandarizando el sistema postal." },
        { frase: "El primer periódico en 1605.", explicacion: "El 'Relation aller Fürnemmen und gedenckwürdigen Historien' (Relación de todas las historias distinguidas y memorables), publicado en Estrasburgo en 1605 por Johann Carolus, es ampliamente considerado el primer periódico impreso regularmente." },
        { frase: "La primera biblioteca pública en 1854.", explicacion: "La Biblioteca Pública de Boston, inaugurada en 1854, es considerada la primera gran biblioteca pública de los Estados Unidos que permitía a los ciudadanos tomar libros prestados y llevarlos a casa, marcando un hito en el acceso público a la información." },
        { frase: "El primer zoológico en 1752.", explicacion: "El Tiergarten Schönbrunn en Viena, Austria, fundado en 1752, es el zoológico más antiguo del mundo aún en funcionamiento. Originalmente era una ménagerie imperial, pero fue abierto al público y se convirtió en un zoológico moderno." },
        { frase: "El primer museo en el siglo III a. C.", explicacion: "El 'Museion' de Alejandría, fundado en el siglo III a. C. en el Egipto ptolemaico, es considerado por muchos como el primer 'museo' en el sentido moderno, aunque era más un centro de investigación y aprendizaje con una biblioteca." },
        { frase: "El primer parque nacional fue Yellowstone.", explicacion: "El Parque Nacional de Yellowstone, establecido en 1872 en los Estados Unidos, fue el primer parque nacional del mundo. Fue creado para preservar sus características geológicas únicas, como géiseres y aguas termales, y su diversa vida silvestre." },
        { frase: "El primer parque de atracciones fue Bakken.", explicacion: "Dyrehavsbakken, o simplemente 'Bakken', cerca de Copenhague, Dinamarca, es el parque de atracciones más antiguo del mundo aún en funcionamiento, fundado en 1583. Originalmente era un lugar donde la gente acudía por un manantial de agua pura y se convirtió en un lugar de entretenimiento." },
        { frase: "El primer centro comercial en 1954.", explicacion: "El Northgate Center, inaugurado en Seattle, Washington, en 1950, es a menudo citado como el primer centro comercial moderno al aire libre. Sin embargo, el Southdale Center en Edina, Minnesota, inaugurado en 1956, es reconocido como el primer centro comercial totalmente cerrado y climatizado en EE. UU." },
        { frase: "El primer restaurante de comida rápida en 1921.", explicacion: "White Castle, fundado en Wichita, Kansas, en 1921, es ampliamente considerado el primer restaurante de comida rápida en Estados Unidos. Se hizo famoso por sus pequeñas hamburguesas cuadradas y su enfoque en la producción en masa y la estandarización." },
        { frase: "La primera pizza en el siglo XVIII.", explicacion: "La pizza tal como la conocemos hoy, con tomate y queso, se originó en Nápoles, Italia, en el siglo XVIII. Era una comida popular y barata para la gente pobre de la ciudad." },
        { frase: "El chocolate es de semillas de cacao.", explicacion: "El chocolate se produce a partir de las semillas del árbol del cacao (Theobroma cacao). Estas semillas se fermentan, secan, tuestan y muelen para crear licor de chocolate, que luego se procesa en los diversos productos de chocolate." },
        { frase: "El café es de granos de la planta del café.", explicacion: "El café es una bebida elaborada a partir de los granos tostados y molidos de la planta del café (Coffea). Se originó en Etiopía y se ha convertido en una de las bebidas más populares del mundo." },
        { frase: "El té es de hojas de la planta del té.", explicacion: "El té es una bebida aromática que se prepara vertiendo agua caliente sobre hojas curadas o frescas de la planta del té (Camellia sinensis). Es la bebida más consumida en el mundo después del agua." },
        { frase: "El vino es de uvas fermentadas.", explicacion: "El vino es una bebida alcohólica que se produce por la fermentación del zumo de uvas. La levadura presente en las uvas convierte los azúcares del zumo en alcohol y dióxido de carbono." },
        { frase: "La cerveza es de granos fermentados.", explicacion: "La cerveza es una bebida alcohólica que se elabora mediante la fermentación de cereales, principalmente cebada malteada. Otros ingredientes comunes incluyen lúpulo (que proporciona amargor y aroma), levadura y agua." },
        { frase: "El whisky es de granos fermentados.", explicacion: "El whisky es una bebida alcohólica destilada hecha de un mosto de cereales fermentado. Los cereales comunes incluyen cebada, maíz, centeno y trigo. Luego se envejece en barriles de madera." },
        { frase: "El vodka es de granos o patatas.", explicacion: "El vodka es una bebida alcohólica destilada que se produce tradicionalmente a partir de la fermentación de granos de cereal o patatas. Se destila a una alta pureza, lo que resulta en un sabor y aroma muy neutros." },
        { frase: "La ginebra es de bayas de enebro.", explicacion: "La ginebra es una bebida alcohólica destilada que obtiene su sabor predominante de las bayas de enebro. A menudo se le añaden otros botánicos para crear perfiles de sabor complejos." },
        { frase: "El ron es de melaza o jugo de caña.", explicacion: "El ron es una bebida alcohólica destilada hecha de subproductos de la caña de azúcar, como la melaza, o directamente del jugo de caña de azúcar. Se envejece en barriles de roble." },
        { frase: "El tequila es de agave.", explicacion: "El tequila es una bebida alcohólica destilada originaria de México, elaborada a partir del agave azul (Agave tequilana Weber azul). Es un tipo de mezcal y tiene una denominación de origen protegida." },
        { frase: "El sistema métrico es metro, kg y segundo.", explicacion: "El Sistema Internacional de Unidades (SI), comúnmente conocido como sistema métrico, se basa en siete unidades básicas: metro (longitud), kilogramo (masa), segundo (tiempo), amperio (corriente eléctrica), kelvin (temperatura), mol (cantidad de sustancia) y candela (intensidad luminosa)." },
        { frase: "El sistema imperial es pie, libra y segundo.", explicacion: "El sistema imperial de unidades es un sistema de unidades de medida que se utilizó oficialmente en el Reino Unido y otros países de la Commonwealth. Incluye unidades como pie, pulgada, libra, milla, galón, etc." },
        { frase: "El primer calendario fue egipcio.", explicacion: "Uno de los primeros calendarios conocidos fue desarrollado por los antiguos egipcios. Era un calendario solar basado en un año de 365 días, dividido en 12 meses de 30 días más 5 días epagómenos, y estaba vinculado a la crecida anual del río Nilo." },
        { frase: "El reloj de sol medía el tiempo.", explicacion: "Un reloj de sol es un instrumento que mide el tiempo observando la posición del Sol. Proyecta una sombra sobre una superficie marcada con horas, lo que permite estimar la hora del día." },
        { frase: "El reloj de agua medía el tiempo.", explicacion: "Un reloj de agua, o clepsidra, era un antiguo dispositivo para medir el tiempo mediante el flujo regulado de agua. El tiempo se medía por la cantidad de agua que goteaba de un recipiente a otro o por el nivel del agua en un recipiente graduado." },
        { frase: "El reloj mecánico es del siglo XIV.", explicacion: "Los primeros relojes mecánicos se desarrollaron en Europa durante el siglo XIV. Estos relojes utilizaban un mecanismo de escape que regulaba la liberación de energía, permitiendo un movimiento regular y la medición del tiempo." },
        { frase: "El reloj de péndulo es del siglo XVII.", explicacion: "El reloj de péndulo fue inventado por Christiaan Huygens en 1656. La oscilación regular de un péndulo proporciona una base mucho más precisa para la medición del tiempo que los mecanismos anteriores, lo que revolucionó la relojería." },
        { frase: "El reloj de cuarzo es del siglo XX.", explicacion: "Los relojes de cuarzo, que utilizan las vibraciones de un cristal de cuarzo para mantener el tiempo, se hicieron comercialmente disponibles en la década de 1960. Son mucho más precisos y asequibles que los relojes mecánicos." },
        { frase: "El reloj atómico es el más preciso.", explicacion: "Los relojes atómicos utilizan la frecuencia de resonancia de un átomo (como el cesio o el rubidio) para mantener el tiempo. Son los dispositivos más precisos para medir el tiempo, con errores de solo un segundo cada millones de años." },
        { frase: "El tiempo es existencia y eventos en secuencia.", explicacion: "Desde una perspectiva filosófica y científica, el tiempo es una dimensión fundamental que permite la sucesión de eventos, el cambio y la percepción de un 'antes' y un 'después'. Es una parte intrínseca de la estructura del universo." }
    ];

    // Función para obtener la frase del día
    function obtenerFraseDelDia() {
        // Obtener el número del día del año
        const now = new Date();
        const start = new Date(now.getFullYear(), 0, 0);
        const diff = (now - start) + ((start.getTimezoneOffset() - now.getTimezoneOffset()) * 60 * 1000);
        const oneDay = 1000 * 60 * 60 * 24;
        const dayOfYear = Math.floor(diff / oneDay);

        // Usar el día del año como índice para obtener la frase (usando el módulo para evitar errores de índice)
        const index = dayOfYear % datosSabiasQue.length;
        return datosSabiasQue[index];
    }

    // Función para mostrar la frase y su explicación en la página
    function mostrarFraseDelDia() {
        const { frase, explicacion } = obtenerFraseDelDia(); // Ahora obtenemos frase y explicación
        fraseElement.textContent = `"${frase}"`;
        explicacionElement.textContent = explicacion; // Asignamos la explicación
    }

    mostrarFraseDelDia();
});